[build] # default master branch
  publish = '_site/'
  command = 'npm run build'
  environment = { ELEVENTY_ENV = 'production', NODE_VERSION = "14" } # to enable Eleventy to know the environment


[context.preview] # 'preview' is the branch name
  publish = '_site/'
  command = 'npm run build'
  environment = { ELEVENTY_ENV = 'preview', NODE_VERSION = "14" } # to enable Eleventy to know the environment
